### ISSUE TITLE
Minor: Rename Dimmer to Fan Speed % on GE Fan DTH

### ISSUE THREAD

**Issue by Skates1616** [mwav3/smartthingscode#1]
The GE Fan DTH references Dimmer for the fan speed percentage.  This should be renamed to Fan Speed %?

**Comment by mwav3** [comment]
Do you mean in the smartapp itself?  I believe this is necessary for Alexa/Google integration.  I could be wrong.  Can you please include a screenshot of where this is or point out where in the code that is incorrect?  Thanks.

**Comment by Skates1616** [comment]
I am referring to the SmartApp:

![B4777803-8936-477D-A46A-D3D1AA462E92](https://user-images.githubusercontent.com/23196661/93289641-781bb380-f7a4-11ea-81ed-ca46870a93d9.jpeg)

**Comment by mwav3** [comment]
Yes, that must be a dimmer for proper Alexa/Google integration, and that's also the way the stock handler should work for this fan.  You wouldn't be able to control the fan with either Alexa or Google without that slider referring to it as a "dimmer".  The dimmer slider will allow you to say "Alexa, set fan to 33%" and that will set the fan to "low speed".  You cannot say to Alexa "set the fan to low" due to limitations in the Alexa smarthome skill itself.

I don't have this fan switch myself so can't test it, so are there any other issues?  Can you set the fan speed properly with the slider and dimmer?  Do you use it with Alexa/Google integration?  Are the buttons for double tap showing up in the smartlighting app (or webcore) if you use that?  I would be interested to know how its working out otherwise.  Thanks for any feedback you can provide.

**Comment by mwav3** [comment]
Leaving this "issue" open for now until someone can verify the fan DTH is working properly.  Please feel free to provide any feedback here on the fan DTH.  Please post issues on any other DTH's separately.  Thanks!

**Comment by Skates1616** [comment]
The DTH definitely works, will confirm if it works with Siri later today.

**Comment by mwav3** [comment]
Closing based on recent updates
