### ISSUE TITLE
GE 46203 association group 3 not acting on tapped device on up_2x, down_2x events

### ISSUE THREAD

**Issue by abahgat** [mwav3/smartthingscode#5]
First of all, thank you for creating the device handler for the new GE switches!

I have just installed the handler for the 46203 dimmer (`smartthingscode/devicetypes/mwav3/ge-46203-dimmer-switch.src/ge-46203-dimmer-switch.groovy`) and I am running into a little bit of trouble with device groups.

I have 3 dimmers that control ceiling lights in my living areas, their ids are `06`, `07` and `08`.
I configured association group 3 to include all 3 (I typed `06,07,08` in the settings screen).
Say all switches are off, when I double tap up on switch `06`, I can see the the other 2 dimmers turning off as requested, but `06` stays off. Based on the logs, it's as if  `06` is not getting any events.

The same happens if I double tap off. Any ideas about what might be happening here?

Here the logs from my last attempt:

```
740981f6-4ac3-4579-9bb5-b8e90881925f 1:03:28 PM: debug Parsed CentralSceneNotification(sceneNumber: 1, keyAttributes: 3, reserved11: 16, sequenceNumber: 192) to ['name':'button', 'value':'up_2x', 'data':['buttonNumber':1], 'descriptionText':Kitchen Lights button up was double tapped, 'isStateChange':true, 'linkText':'Kitchen Lights', 'displayed':true]
740981f6-4ac3-4579-9bb5-b8e90881925f 1:03:28 PM: debug ---Central Scene Command--- Kitchen Lights sent CentralSceneNotification(sceneNumber: 1, keyAttributes: 3, reserved11: 16, sequenceNumber: 192)
740981f6-4ac3-4579-9bb5-b8e90881925f 1:03:28 PM: debug description: zw device: 06, command: 5B03, payload: C0 83 01
c0c25f97-1690-4c69-8448-1b093a9fe017 1:03:26 PM: debug Parsed SwitchMultilevelReport(value: 80) to [['name':'switch', 'value':'on', 'type':'physical', 'linkText':'Dining Table Lights', 'descriptionText':Dining Table Lights switch is on, 'isStateChange':true, 'displayed':true], ['name':'level', 'value':80, 'unit':'%', 'type':'physical', 'linkText':'Dining Table Lights', 'descriptionText':Dining Table Lights level is 80%, 'isStateChange':false, 'displayed':false]]
c0c25f97-1690-4c69-8448-1b093a9fe017 1:03:26 PM: debug description: zw device: 08, command: 2603, payload: 50
c0c25f97-1690-4c69-8448-1b093a9fe017 1:03:26 PM: debug description: zw device: 08, command: 2603, payload: 50
76fbf83a-146b-46c0-8c96-2e6c53b54d8f 1:03:25 PM: debug Parsed SwitchMultilevelReport(value: 50) to [['name':'switch', 'value':'on', 'type':'physical', 'linkText':'Living Room Lights', 'descriptionText':Living Room Lights switch is on, 'isStateChange':true, 'displayed':true], ['name':'level', 'value':50, 'unit':'%', 'type':'physical', 'linkText':'Living Room Lights', 'descriptionText':Living Room Lights level is 50%, 'isStateChange':false, 'displayed':false]]
76fbf83a-146b-46c0-8c96-2e6c53b54d8f 1:03:25 PM: debug description: zw device: 07, command: 2603, payload: 32
```

**Comment by mwav3** [comment]
If you're trying to do a direct association with another Zwave device, they both need to be the same level of security.  If one device is S2 encrypted, and the other is S2 failed, or ZWAVE_LEGACY_NON_SECURE, they will not be able to communicate with eachother.  If all devices are S2 capable and one failed, you'll need to exclude, and reinclude it being sure to scan the QR code during inclusion.  If all devices don't support S2 inclusion, you can exclude the S2 secure device, and not scan the barcode, forcing it to downgrade the security and communicate with older non S2 devices.  Because 2 of your 3 devices work to associate, I highly suspect the security settings not being on the same page as the problem.

Workaround also could be just to use an automations (automation screen in new app, smartlighting, or webcore) to control the third light that can't be controlled by association.  Also, the trigger of direct associations between this switch and other devices will not show in the logs, as they bypass the hub entirely and the devices communicate direct with each other.  Generally when the device turns on, it then communicates back to the hub that it turned on/off, but that's after the fact and could be delayed.

To further diagnose if its a security issue you can attach screenshots of the device's data box obtained from the IDE.  Let me know what you find.

**Comment by mwav3** [comment]
Closing issue as problems appear unrelated to the code of the device handler
